from PyQt5 import QtCore, QtGui, QtWidgets
import math


class Ui_ParallelogramWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Parallelogram")
        MainWindow.resize(1000, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 900))
        MainWindow.setStyleSheet("margin: 0;\n"
                                 "padding: 0;\n"
                                 "border: none")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("* {\n"
                                         "    background-color: #c0c0c0;\n"
                                         "    color: black;\n"
                                         "    border: none\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton {\n"
                                         "    background-color: LightSlateGray;\n"
                                         "    border-radius: 5px;\n"
                                         "}\n"
                                         "QPushButton:hover{\n"
                                         "    background-color: LightGray;\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:pressed{\n"
                                         "    background-color: grey;\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_2.setStyleSheet("background-color: grey")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_23 = QtWidgets.QFrame(self.frame_10)
        self.frame_23.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_23)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_21.addWidget(self.checkBox_3)
        self.horizontalLayout_6.addWidget(self.frame_23, 0, QtCore.Qt.AlignLeft)
        self.frame_14 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_3.setContentsMargins(-1, -1, 30, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_14)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../Images/parallelogram_cl.png"))
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_6.addWidget(self.frame_14)
        self.horizontalLayout_4.addWidget(self.frame_10, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_4.addWidget(self.frame_8, 0, QtCore.Qt.AlignTop)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_13 = QtWidgets.QFrame(self.frame_9)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_1 = QtWidgets.QFrame(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_1.sizePolicy().hasHeightForWidth())
        self.frame_1.setSizePolicy(sizePolicy)
        self.frame_1.setMaximumSize(QtCore.QSize(468, 16777215))
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_20 = QtWidgets.QFrame(self.frame_1)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.horizontalLayout_7.addWidget(self.frame_20, 0, QtCore.Qt.AlignLeft)
        self.frame_21 = QtWidgets.QFrame(self.frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_21.sizePolicy().hasHeightForWidth())
        self.frame_21.setSizePolicy(sizePolicy)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_15.addWidget(self.lineEdit)
        self.horizontalLayout_7.addWidget(self.frame_21)
        self.verticalLayout_5.addWidget(self.frame_1)
        self.frame_16 = QtWidgets.QFrame(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setMaximumSize(QtCore.QSize(468, 16777215))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_30 = QtWidgets.QFrame(self.frame_16)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_12 = QtWidgets.QLabel(self.frame_30)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        self.horizontalLayout_13.addWidget(self.frame_30, 0, QtCore.Qt.AlignLeft)
        self.frame_31 = QtWidgets.QFrame(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_31.sizePolicy().hasHeightForWidth())
        self.frame_31.setSizePolicy(sizePolicy)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_31)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_16.addWidget(self.lineEdit_2)
        self.horizontalLayout_13.addWidget(self.frame_31)
        self.verticalLayout_5.addWidget(self.frame_16)
        self.frame_19 = QtWidgets.QFrame(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_19.sizePolicy().hasHeightForWidth())
        self.frame_19.setSizePolicy(sizePolicy)
        self.frame_19.setMaximumSize(QtCore.QSize(468, 16777215))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_32 = QtWidgets.QFrame(self.frame_19)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.frame_32)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        self.horizontalLayout_15.addWidget(self.frame_32, 0, QtCore.Qt.AlignLeft)
        self.frame_33 = QtWidgets.QFrame(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_33.sizePolicy().hasHeightForWidth())
        self.frame_33.setSizePolicy(sizePolicy)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_33)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_17.addWidget(self.lineEdit_3)
        self.horizontalLayout_15.addWidget(self.frame_33)
        self.verticalLayout_5.addWidget(self.frame_19)
        self.frame_100 = QtWidgets.QFrame(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_100.sizePolicy().hasHeightForWidth())
        self.frame_100.setSizePolicy(sizePolicy)
        self.frame_100.setMaximumSize(QtCore.QSize(468, 16777215))
        self.frame_100.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_100.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_100.setObjectName("frame_100")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_100)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.frame_101 = QtWidgets.QFrame(self.frame_100)
        self.frame_101.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_101.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_101.setObjectName("frame_101")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_101)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_6 = QtWidgets.QLabel(self.frame_101)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_25.addWidget(self.label_6)
        self.horizontalLayout_23.addWidget(self.frame_101, 0, QtCore.Qt.AlignLeft)
        self.frame_102 = QtWidgets.QFrame(self.frame_100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_102.sizePolicy().hasHeightForWidth())
        self.frame_102.setSizePolicy(sizePolicy)
        self.frame_102.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_102.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_102.setObjectName("frame_102")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_102)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_102)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_22.addWidget(self.lineEdit_6)
        self.horizontalLayout_23.addWidget(self.frame_102)
        self.verticalLayout_5.addWidget(self.frame_100)
        self.horizontalLayout_10.addWidget(self.frame_13)
        self.frame_15 = QtWidgets.QFrame(self.frame_9)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_200 = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_200.sizePolicy().hasHeightForWidth())
        self.frame_200.setSizePolicy(sizePolicy)
        self.frame_200.setMaximumSize(QtCore.QSize(468, 16777215))
        self.frame_200.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_200.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_200.setObjectName("frame_200")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_200)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.frame_201 = QtWidgets.QFrame(self.frame_200)
        self.frame_201.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_201.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_201.setObjectName("frame_201")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_201)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_7 = QtWidgets.QLabel(self.frame_201)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_27.addWidget(self.label_7)
        self.horizontalLayout_26.addWidget(self.frame_201, 0, QtCore.Qt.AlignLeft)
        self.frame_202 = QtWidgets.QFrame(self.frame_200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_202.sizePolicy().hasHeightForWidth())
        self.frame_202.setSizePolicy(sizePolicy)
        self.frame_202.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_202.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_202.setObjectName("frame_202")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_202)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_202)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_23.addWidget(self.lineEdit_7)
        self.horizontalLayout_26.addWidget(self.frame_202)
        self.verticalLayout_7.addWidget(self.frame_200)
        self.frame_300 = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_300.sizePolicy().hasHeightForWidth())
        self.frame_300.setSizePolicy(sizePolicy)
        self.frame_300.setMaximumSize(QtCore.QSize(468, 16777215))
        self.frame_300.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_300.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_300.setObjectName("frame_300")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_300)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.frame_301 = QtWidgets.QFrame(self.frame_300)
        self.frame_301.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_301.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_301.setObjectName("frame_301")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_301)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_11 = QtWidgets.QLabel(self.frame_301)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_31.addWidget(self.label_11)
        self.horizontalLayout_30.addWidget(self.frame_301, 0, QtCore.Qt.AlignLeft)
        self.frame_302 = QtWidgets.QFrame(self.frame_300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_302.sizePolicy().hasHeightForWidth())
        self.frame_302.setSizePolicy(sizePolicy)
        self.frame_302.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_302.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_302.setObjectName("frame_302")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_302)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_302)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_25.addWidget(self.lineEdit_9)
        self.horizontalLayout_30.addWidget(self.frame_302)
        self.verticalLayout_7.addWidget(self.frame_300)
        self.frame_34 = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_34.sizePolicy().hasHeightForWidth())
        self.frame_34.setSizePolicy(sizePolicy)
        self.frame_34.setMaximumSize(QtCore.QSize(468, 16777215))
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_35 = QtWidgets.QFrame(self.frame_34)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_14 = QtWidgets.QLabel(self.frame_35)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_18.addWidget(self.label_14)
        self.horizontalLayout_17.addWidget(self.frame_35, 0, QtCore.Qt.AlignLeft)
        self.frame_36 = QtWidgets.QFrame(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_36.sizePolicy().hasHeightForWidth())
        self.frame_36.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.frame_36.setFont(font)
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_36)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_36)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_18.addWidget(self.lineEdit_4)
        self.horizontalLayout_17.addWidget(self.frame_36)
        self.verticalLayout_7.addWidget(self.frame_34)
        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setMaximumSize(QtCore.QSize(468, 16777215))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_37 = QtWidgets.QFrame(self.frame_17)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_37)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_15 = QtWidgets.QLabel(self.frame_37)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_20.addWidget(self.label_15)
        self.horizontalLayout_19.addWidget(self.frame_37, 0, QtCore.Qt.AlignLeft)
        self.frame_38 = QtWidgets.QFrame(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_38.sizePolicy().hasHeightForWidth())
        self.frame_38.setSizePolicy(sizePolicy)
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_38)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_38)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_19.addWidget(self.lineEdit_5)
        self.horizontalLayout_19.addWidget(self.frame_38)
        self.verticalLayout_7.addWidget(self.frame_17)
        self.horizontalLayout_10.addWidget(self.frame_15)
        self.verticalLayout_6.addWidget(self.frame_9)
        self.frame_12 = QtWidgets.QFrame(self.frame_7)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_12, clicked=lambda: self.result())
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_12, clicked=lambda: self.update())
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 1))
        self.pushButton_3.setMaximumSize(QtCore.QSize(100000, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.frame_12)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.verticalLayout_6.addWidget(self.frame_12, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame)
        self.parallelogram = 'cl'
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Parallelogram"))
        self.label_2.setText(_translate("MainWindow", "Parallelogram"))
        self.label.setText(_translate("MainWindow", "Geometric Calculator"))
        self.checkBox_3.setText(_translate("MainWindow", "Rhombus"))
        self.label_4.setText(_translate("MainWindow", "a:"))
        self.lineEdit.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "b:"))
        self.lineEdit_2.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "d1:"))
        self.lineEdit_3.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "d2:"))
        self.lineEdit_6.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "h1:"))
        self.lineEdit_7.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "h2:"))
        self.lineEdit_9.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "S:"))
        self.lineEdit_4.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "P:"))
        self.lineEdit_5.setText(_translate("MainWindow", "0"))
        self.pushButton_2.setText(_translate("MainWindow", "Results"))
        self.pushButton_3.setText(_translate("MainWindow", "Update/Nullify"))
        self.pushButton.setText(_translate("MainWindow", "Menu"))

    def errors(self):
        self.label_3.setPixmap(QtGui.QPixmap("../Images/error.png"))
        self.pushButton_2.hide()

    def nullify(self):
        self.lineEdit.setText("0")
        self.lineEdit_2.setText("0")
        self.lineEdit_3.setText("0")
        self.lineEdit_4.setText("0")
        self.lineEdit_5.setText("0")
        self.lineEdit_6.setText("0")
        self.lineEdit_7.setText("0")
        self.lineEdit_9.setText("0")

    def update(self):
        self.nullify()
        self.pushButton_2.show()
        if self.checkBox_3.isChecked():
            self.parallelogram = 'rb'
            self.label_3.setPixmap(QtGui.QPixmap("../Images/parallelogram_rb.png"))
            self.frame_16.hide()
            self.frame_300.hide()
            self.label_7.setText("h:")
        else:
            self.parallelogram = 'cl'
            self.label_3.setPixmap(QtGui.QPixmap("../Images/parallelogram_cl.png"))
            self.frame_16.show()
            self.frame_300.show()
            self.label_7.setText("h1:")

    def result(self):
        a = float(self.lineEdit.text())
        b = float(self.lineEdit_2.text())
        d1 = float(self.lineEdit_3.text())
        d2 = float(self.lineEdit_6.text())
        h1 = float(self.lineEdit_7.text())
        h2 = float(self.lineEdit_9.text())
        S = float(self.lineEdit_4.text())
        P = float(self.lineEdit_5.text())
        for _ in range(10):
            if self.parallelogram == 'cl':
                # добавь P
                if a and b:
                    P = 2 * (a + b)
                if a and P:
                    b = (P - 2 * a) / 2
                if b and P:
                    a = (P - 2 * b) / 2

                if S and b:
                    h2 = S / b
                if S and a:
                    h1 = S / a

                if a and h1:
                    S = a * h1
                if b and h2:
                    S = b * h2

                if S and h1:
                    a = S / h1
                if S and h2:
                    b = S / h2

                if h2 and a and b:
                    al = math.asin(h2 / a)
                    bet = math.pi - al

                    d1 = (a ** 2 + b ** 2 - 2 * a * b * math.cos(bet)) ** 0.5
                    d2 = (a ** 2 + b ** 2 - 2 * a * b * math.cos(al)) ** 0.5

                if h1 and a and b:
                    al = math.asin(h1 / b)
                    bet = math.pi - al

                    d1 = (a ** 2 + b ** 2 - 2 * a * b * math.cos(bet)) ** 0.5
                    d2 = (a ** 2 + b ** 2 - 2 * a * b * math.cos(al)) ** 0.5
            if self.parallelogram == 'rb':
                if a:
                    b = a
                elif b:
                    a = b

                if P:
                    a = P / 4
                if a and b:
                    P = 2 * (a + b)
                if a and P:
                    b = (P - 2 * a) / 2
                if b and P:
                    a = (P - 2 * b) / 2

                if S and b:
                    h2 = S / b
                if S and a:
                    h1 = S / a

                if a and h1:
                    S = a * h1
                if b and h2:
                    S = b * h2

                if S and h1:
                    a = S / h1
                if S and h2:
                    b = S / h2

                if h2 and a and b:
                    al = math.asin(h2 / a)
                    bet = math.pi - al

                    d1 = (a ** 2 + b ** 2 - 2 * a * b * math.cos(bet)) ** 0.5
                    d2 = (a ** 2 + b ** 2 - 2 * a * b * math.cos(al)) ** 0.5

                if h1 and a and b:
                    al = math.asin(h1 / b)
                    bet = math.pi - al

                    d1 = (a ** 2 + b ** 2 - 2 * a * b * math.cos(bet)) ** 0.5
                    d2 = (a ** 2 + b ** 2 - 2 * a * b * math.cos(al)) ** 0.5
            a = round(a, 4)
            b = round(b, 4)
            d1 = round(d1, 4)
            d2 = round(d2, 4)
            h1 = round(h1, 4)
            h2 = round(h2, 4)
            S = round(S, 4)
            P = round(P, 4)
        # =======================================
        # ERRORS
        # =======================================

        fl_a = a != float(self.lineEdit.text()) and float(self.lineEdit.text()) != 0
        fl_b = b != float(self.lineEdit_2.text()) and float(self.lineEdit_2.text()) != 0
        fl_d1 = d1 != float(self.lineEdit_3.text()) and float(self.lineEdit_3.text()) != 0
        fl_d2 = d2 != float(self.lineEdit_6.text()) and float(self.lineEdit_6.text()) != 0
        fl_h1 = h1 != float(self.lineEdit_7.text()) and float(self.lineEdit_7.text()) != 0
        fl_h2 = h2 != float(self.lineEdit_9.text()) and float(self.lineEdit_9.text()) != 0
        fl_S = S != float(self.lineEdit_4.text()) and float(self.lineEdit_4.text()) != 0
        fl_P = P != float(self.lineEdit_5.text()) and float(self.lineEdit_5.text()) != 0
        if fl_a or fl_b or fl_d1 or fl_h2 or fl_h2 or fl_d2 or fl_P or fl_S:
            self.errors()
            return
        self.lineEdit.setText(str(round(a, 4)))
        self.lineEdit_2.setText(str(round(b, 4)))
        self.lineEdit_3.setText(str(round(d1, 4)))
        self.lineEdit_4.setText(str(round(S, 4)))
        self.lineEdit_5.setText(str(round(P, 4)))
        self.lineEdit_6.setText(str(round(d2, 4)))
        self.lineEdit_7.setText(str(round(h1, 4)))
        self.lineEdit_9.setText(str(round(h2, 4)))
